// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"@@/global-layout","id":"1"},"2":{"path":"/login","name":"登录页面","parentId":"@@/global-layout","id":"2"},"3":{"path":"/register","name":"注册会员","parentId":"@@/global-layout","id":"3"},"4":{"path":"/home","name":"主页","parentId":"@@/global-layout","id":"4"},"5":{"path":"/about","name":"刊物介绍","parentId":"@@/global-layout","id":"5"},"6":{"path":"/guidelines","name":"投稿须知","parentId":"@@/global-layout","id":"6"},"7":{"path":"/member","name":"会员首页","access":"canSeeMember","parentId":"@@/global-layout","id":"7"},"8":{"path":"/member/post-paper","access":"canSeeMember","parentId":"7","id":"8"},"9":{"path":"/member/profile","access":"canSeeMember","parentId":"7","id":"9"},"10":{"path":"/member/submissions","access":"canSeeMember","parentId":"7","id":"10"},"11":{"path":"/editor","name":"编辑首页","access":"canSeeEditor","parentId":"@@/global-layout","id":"11"},"12":{"path":"/edtior/profile","access":"canSeeEditor","parentId":"11","id":"12"},"13":{"path":"/editor/review-paper","access":"canSeeEditor","parentId":"11","id":"13"},"14":{"path":"/admin","name":"管理员首页","access":"canSeeAdmin","parentId":"@@/global-layout","id":"14"},"15":{"path":"/admin/manage-users","access":"canSeeAdmin","parentId":"14","id":"15"},"16":{"path":"*","parentId":"@@/global-layout","id":"16"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Register__index" */'@/pages/Register/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__About__index" */'@/pages/About/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Guidelines__index" */'@/pages/Guidelines/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Member__PostPaper__index" */'@/pages/Member/PostPaper/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Member__Profile__index" */'@/pages/Member/Profile/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Member__Submissions__index" */'@/pages/Member/Submissions/index.tsx')),
'11': React.lazy(() => import('./EmptyRoute')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Editor__Profile__index" */'@/pages/Editor/Profile/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Editor__ReviewPaper__index" */'@/pages/Editor/ReviewPaper/index.tsx')),
'14': React.lazy(() => import('./EmptyRoute')),
'15': React.lazy(() => import(/* webpackChunkName: "p__Admin__ManageUsers__index" */'@/pages/Admin/ManageUsers/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__NotFound__index" */'@/pages/NotFound/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/tanxinyu/meiteng/tougao/src/layouts/index.tsx')),
},
  };
}
